## Building a Neural Network from scratch

So let's build a neural network from scratch. We'll use just basic python and NumPy library to achieve this.

The first thing that we have to know is how a basic NN(Neural Network) looks like.


<img src="https://i.stack.imgur.com/sCLdl.png" width="600">


As you can see there is an input layer which get's its input values from a certain dataset.
And then each of the inputs get multiplied by some weight and then a bias is added to it when they are fed into the next set of neurons(i.e. hidden layer).

Next there are activation functions taking care of nonlinearity and interaction effects and then we give an output. Then the loss function tries to find how far off are the outputs from the actual outputs and then it uses some optimisation function to update the weights and biases to get better outputs.

We will go step by step and form a full-fledged NN network.

### Singular output

Firstly, let's imagine that there are 4 input features and only one output neuron. And each of those connections have a different weight associated with it. Also, there is a bias associated with the output neuron.

In [1]:
inputs = [1, 2, 3, 2.5]
weights = [.2, .3, -.5, .9]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

3.55


Here you can see that each of the element in the input vector goes through an element wise multiplication with the weights vector. And finally we add the bias associated with that particular output neuron and print it.

### Multiple outputs

As you can see from the above image that if there is only one output then we don't create enough complexity in the network to actually map the whole picture. So, we need to have hidden layers in between the output and input layers which will certainly have multiple neurons (i.e. multiple outputs).

In [2]:
inputs = [1, 2, 3, 2.5]

weights0 = [.2, .3, -.5, .9]
weights1 = [.24, .43, -9.54, .19]
weights2 = [.27, 7.3, -4.5, 4.9]

bias0 = 2
bias1 = 3
bias2 = 0.5

We have here 4 inputs, and then 3 sets of weights as there are 3 outputs(say). Then we have 3 biases each connected to a particular neuron.

In [3]:
%time

output0 = inputs[0]*weights0[0] + inputs[1]*weights0[1] + inputs[2]*weights0[2] + inputs[3]*weights0[3] + bias0 
output1 = inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1 
output2 = inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2 
print ("{:.2f}, {:.2f}, {:.2f}".format(output0, output1, output2))

Wall time: 0 ns
3.55, -24.04, 14.12


As we have done earlier we do element wise multiplication; add them and then we add bias to it at the end. So we get all the outputs.

### Doing it a smarter way

In the previous example we did the same element wise multiplication, then addition and finally added the bias to it. It's too much of code. So, let's do it with the help of iteration using `for` loops.

In [4]:
weights = [[.2, .3, -.5, .9],
           [.24, .43, -9.54, .19],
           [.27, 7.3, -4.5, 4.9]]

biases = [2, 3, 0.5]

In [5]:
output_layer = []

for weight,bias in zip(weights, biases):
  output = 0
  for k,l in zip(inputs, weight):
    output += k*l
  output += bias
  output_layer.append(output)

In [6]:
print ("{:.2f}, {:.2f}, {:.2f}".format(output_layer[0], output_layer[1], output_layer[2]))

3.55, -24.04, 14.12


So basically we have done the same using `for` loop and then printing it out. I kept the inputs, weights and biases same so that the answer can be verified.

### Using Dot Product

We have done element wise multiplication followed by addition in the previous cells. In vector terms that is basically a [**dot product**](https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length). 

We can use python NumPy library to do quick dot product as you can see I have done below. And again the answer's the same which means it works.

In [7]:
import numpy as np

output = np.dot(weights,inputs) + biases
output

array([  3.55 , -24.045,  14.12 ])

### Multiple inputs

Now it's for sure that can't be just one row of input for any dataset. So we take multiple rows of data as input. And then we obtain the dot product using `np.dot` function and passing in `input_mul` and `weights`. 

But there is a trick here. Since the shape of `input_mul` is (3,4) and the shape of `weights` is also (3,4) so the dot product is not possible. We need to transpose the `weights` matrix so that the shape is changed to (4,3). Now we will be able to perform the dot product.

In [8]:
input_mul = [[1,2,3,2.5],
           [-2.4,7,3.43,-2.3],
           [-4.6,.2,.3,7.3]]

output = np.dot(input_mul, np.array(weights).T) + biases
output

array([[  3.55  , -24.045 ,  14.12  ],
       [ -0.165 , -27.7252,  24.247 ],
       [  7.56  ,   0.507 ,  35.138 ]])

Let's now make this output layer a hidden layer and add another layer that will be the final layer. We add `weights2` and `biases2`. Do the same dot product twice and then we get the output.

In [9]:
weights2 = [[-.2, 4.3, .5],
           [3.2, -.43, 3.19],
           [3.27, 3.5, -4.9]]

biases2 = [1, 4, -0.5]

output_layer1 = np.dot(input_mul, np.array(weights).T) + biases
output_layer2 = np.dot(output_layer1, np.array(weights2).T) + biases2
output_layer2

array([[ -96.0435  ,   70.74215 , -142.237   ],
       [-106.06186 ,   92.741766, -216.88805 ],
       [  19.2371  ,  140.06421 , -146.1805  ]])

And thus we have finally created the structure of a NN.

### Adding ReLU

We will finally pass the outputs of the neurons through an activation function and then finally get an output in the 2nd layer of outputs.

The `Layers` class has the weights, biases and also the `forward` method where we get the dot product added to the biases.
We also have the `ActReLU` method that consists the activation function ReLU. 

We take the inputs(X), pass it through `Layers.forward()`. Then pass the outputs through activation function and then pass those outputs through `Layers.forward()` to get the final output.

In [12]:
X = [[1.9,-22,-41.3,120.9],
     [-0.3,20.4,12.5,-0.4],
     [8.33,50.5,1.3,300.6]]

np.random.seed(10)


class Layers:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
        self.biases = np.arange(n_neurons).reshape(1, n_neurons)
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class ActReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

layer1 = Layers(4,16)
activation1 = ActReLU()
layer2 = LayerDense(16,2)

layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
layer2.output

array([[ 2.72274344,  4.13052163],
       [ 0.07976996, -0.3646472 ],
       [ 1.32626998, 13.42650492]])